// src/lib/constants/genius-pro.ts

export const GENIUS_PRO_DISCLAIMERS = {
  general: {
    es: `⚠️ AVISO LEGAL IMPORTANTE

Los documentos generados por IP-GENIUS PRO son BORRADORES orientativos que requieren revisión profesional.

NO CONSTITUYEN:
• Asesoramiento legal vinculante
• Documentos oficiales listos para presentar
• Traducciones juradas o certificadas

RECOMENDACIONES:
• Revise siempre el contenido con un profesional de PI cualificado
• Verifique las citas legales antes de presentar
• Las traducciones requieren certificación por traductor jurado oficial

IP-NEXUS no se responsabiliza de errores, omisiones o consecuencias derivadas del uso de estos documentos.`,
    en: `⚠️ IMPORTANT LEGAL NOTICE

Documents generated by IP-GENIUS PRO are DRAFT guidelines requiring professional review.

THEY DO NOT CONSTITUTE:
• Binding legal advice
• Official documents ready for filing
• Sworn or certified translations

RECOMMENDATIONS:
• Always review content with a qualified IP professional
• Verify legal citations before filing
• Translations require certification by official sworn translator

IP-NEXUS is not responsible for errors, omissions, or consequences arising from use of these documents.`,
  },
  
  opposition: {
    es: `Este borrador de oposición es un documento de trabajo. 
Antes de presentarlo ante la oficina correspondiente:
1. Verifique todas las citas legales y jurisprudenciales
2. Confirme los plazos vigentes
3. Consulte con un agente de PI registrado
4. Las tasas indicadas son orientativas y pueden haber cambiado`,
    en: `This opposition draft is a working document.
Before filing with the relevant office:
1. Verify all legal and case law citations
2. Confirm current deadlines
3. Consult with a registered IP agent
4. Indicated fees are approximate and may have changed`,
  },
  
  ceaseDesist: {
    es: `Esta carta modelo es un documento de trabajo.
Antes de enviarla:
1. Verifique los datos del destinatario
2. Confirme sus derechos de PI
3. Consulte con un abogado sobre la estrategia
4. Considere las implicaciones de enviar la carta`,
    en: `This template letter is a working document.
Before sending:
1. Verify recipient details
2. Confirm your IP rights
3. Consult with an attorney about strategy
4. Consider the implications of sending the letter`,
  },
};

export const DOCUMENT_TYPES = [
  { id: 'opposition', label: 'Oposición de marca', description: 'Genera un borrador de oposición contra una solicitud de marca', icon: 'Scale' },
  { id: 'cease_desist', label: 'Carta de cese y desistimiento', description: 'Genera una carta exigiendo el cese de uso de una marca', icon: 'FileWarning' },
  { id: 'response_office_action', label: 'Respuesta a Office Action', description: 'Genera una respuesta a una acción oficial de la oficina', icon: 'Reply' },
  { id: 'appeal', label: 'Recurso', description: 'Genera un borrador de recurso contra una decisión', icon: 'Gavel' },
  { id: 'license_draft', label: 'Borrador de licencia', description: 'Genera un borrador de contrato de licencia', icon: 'FileSignature' },
  { id: 'assignment_draft', label: 'Borrador de cesión', description: 'Genera un borrador de contrato de cesión de marca', icon: 'ArrowRightLeft' },
  { id: 'infringement_notice', label: 'Notificación de infracción', description: 'Genera una notificación formal de infracción', icon: 'AlertTriangle' },
  { id: 'coexistence_agreement', label: 'Acuerdo de coexistencia', description: 'Genera un borrador de acuerdo de coexistencia', icon: 'Handshake' },
  { id: 'observations', label: 'Observaciones de tercero', description: 'Genera observaciones contra una solicitud publicada', icon: 'Eye' },
  { id: 'cancellation', label: 'Solicitud de cancelación', description: 'Genera una solicitud de cancelación de marca', icon: 'XCircle' },
] as const;

export const DOCUMENT_TONES = [
  { id: 'diplomatic', label: 'Diplomático', description: 'Tono conciliador, ideal para posible coexistencia' },
  { id: 'professional', label: 'Profesional', description: 'Tono neutro y técnico (recomendado)' },
  { id: 'aggressive', label: 'Contundente', description: 'Tono firme y directo para litigios' },
] as const;

export const IP_OFFICES = [
  { code: 'EUIPO', name: 'EUIPO (UE)', jurisdiction: 'EU' },
  { code: 'OEPM', name: 'OEPM (España)', jurisdiction: 'ES' },
  { code: 'USPTO', name: 'USPTO (EE.UU.)', jurisdiction: 'US' },
  { code: 'UKIPO', name: 'UKIPO (Reino Unido)', jurisdiction: 'GB' },
  { code: 'INPI', name: 'INPI (Francia)', jurisdiction: 'FR' },
  { code: 'DPMA', name: 'DPMA (Alemania)', jurisdiction: 'DE' },
  { code: 'WIPO', name: 'WIPO (Internacional)', jurisdiction: 'INT' },
] as const;

export const OPPOSITION_GROUNDS = [
  { id: 'likelihood_confusion', label: 'Riesgo de confusión (Art. 8.1.b RMUE)', article: 'Art. 8.1.b', description: 'Similitud de signos y productos/servicios que pueda causar confusión en el público' },
  { id: 'reputation', label: 'Marca renombrada (Art. 8.5 RMUE)', article: 'Art. 8.5', description: 'Aprovechamiento indebido o perjuicio al renombre de una marca notoria' },
  { id: 'bad_faith', label: 'Mala fe del solicitante', article: 'Art. 59.1.b', description: 'El solicitante conocía la marca anterior y actúa de mala fe' },
  { id: 'descriptive', label: 'Carácter descriptivo', article: 'Art. 7.1.c', description: 'La marca es descriptiva de los productos o servicios' },
] as const;

export const RISK_LEVEL_CONFIG: Record<string, { color: string; bgColor: string; label: string }> = {
  critical: { color: '#dc2626', bgColor: 'bg-red-100', label: 'CRÍTICO' },
  high: { color: '#ea580c', bgColor: 'bg-orange-100', label: 'ALTO' },
  medium: { color: '#ca8a04', bgColor: 'bg-yellow-100', label: 'MODERADO' },
  low: { color: '#16a34a', bgColor: 'bg-green-100', label: 'BAJO' },
};
