// Re-export from types for backward compatibility
export { 
  INTEGRATION_PROVIDERS, 
  INTEGRATION_CATEGORIES,
  type IntegrationProvider,
  type IntegrationConnection,
  type IntegrationCategory,
  type IntegrationField
} from '@/types/integrations';

export const WEBHOOK_SOURCES = {
  stripe: { name: 'Stripe', events: [
    'checkout.session.completed',
    'invoice.paid',
    'invoice.payment_failed',
    'customer.subscription.created',
    'customer.subscription.updated',
    'customer.subscription.deleted',
  ]},
  resend: { name: 'Resend', events: [
    'email.sent',
    'email.delivered',
    'email.bounced',
    'email.complained',
  ]},
} as const;

export const EMAIL_TEMPLATE_CODES = {
  welcome: 'Bienvenida',
  invitation: 'Invitación al equipo',
  password_reset: 'Restablecer contraseña',
  renewal_reminder: 'Recordatorio de renovación',
  invoice_sent: 'Factura enviada',
  deadline_alert: 'Alerta de plazo',
  watch_alert: 'Alerta de vigilancia',
  campaign: 'Campaña de marketing',
} as const;

export const NICE_CLASSES_SHORT: Record<number, string> = {
  1: 'Productos químicos',
  2: 'Pinturas',
  3: 'Cosméticos',
  4: 'Combustibles',
  5: 'Productos farmacéuticos',
  6: 'Metales',
  7: 'Máquinas',
  8: 'Herramientas',
  9: 'Electrónica',
  10: 'Aparatos médicos',
  11: 'Iluminación',
  12: 'Vehículos',
  13: 'Armas',
  14: 'Joyería',
  15: 'Instrumentos musicales',
  16: 'Papel',
  17: 'Caucho',
  18: 'Cuero',
  19: 'Materiales construcción',
  20: 'Muebles',
  21: 'Utensilios domésticos',
  22: 'Cuerdas y toldos',
  23: 'Hilos',
  24: 'Tejidos',
  25: 'Ropa',
  26: 'Mercería',
  27: 'Alfombras',
  28: 'Juguetes',
  29: 'Alimentos procesados',
  30: 'Café, té, pastelería',
  31: 'Productos agrícolas',
  32: 'Bebidas',
  33: 'Bebidas alcohólicas',
  34: 'Tabaco',
  35: 'Publicidad',
  36: 'Finanzas',
  37: 'Construcción',
  38: 'Telecomunicaciones',
  39: 'Transporte',
  40: 'Tratamiento materiales',
  41: 'Educación',
  42: 'Tecnología',
  43: 'Hostelería',
  44: 'Servicios médicos',
  45: 'Servicios jurídicos',
};

export const IP_OFFICES = [
  { code: 'EM', name: 'EUIPO', flag: '🇪🇺', region: 'europe' },
  { code: 'ES', name: 'OEPM (España)', flag: '🇪🇸', region: 'europe' },
  { code: 'US', name: 'USPTO', flag: '🇺🇸', region: 'americas' },
  { code: 'GB', name: 'UKIPO', flag: '🇬🇧', region: 'europe' },
  { code: 'DE', name: 'DPMA (Alemania)', flag: '🇩🇪', region: 'europe' },
  { code: 'FR', name: 'INPI (Francia)', flag: '🇫🇷', region: 'europe' },
  { code: 'IT', name: 'UIBM (Italia)', flag: '🇮🇹', region: 'europe' },
  { code: 'PT', name: 'INPI (Portugal)', flag: '🇵🇹', region: 'europe' },
  { code: 'CN', name: 'CNIPA (China)', flag: '🇨🇳', region: 'asia' },
  { code: 'JP', name: 'JPO (Japón)', flag: '🇯🇵', region: 'asia' },
  { code: 'KR', name: 'KIPO (Corea)', flag: '🇰🇷', region: 'asia' },
  { code: 'MX', name: 'IMPI (México)', flag: '🇲🇽', region: 'americas' },
  { code: 'BR', name: 'INPI (Brasil)', flag: '🇧🇷', region: 'americas' },
  { code: 'AU', name: 'IP Australia', flag: '🇦🇺', region: 'oceania' },
] as const;
