/**
 * Hook para obtener el menú del sidebar dinámicamente desde la BD
 * Agrupa módulos por secciones y respeta licencias
 */

import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrganization } from "@/contexts/organization-context";

// Datos estáticos de fallback mientras se arregla la BD
const STATIC_SIDEBAR_DATA: SidebarSection[] = [
  // Dashboard - sección especial, siempre visible sin colapsable
  {
    sectionCode: "dashboard",
    sectionName: "Dashboard",
    sectionLabel: "Panel",
    sectionIcon: "LayoutDashboard",
    sectionOrder: 1,
    sectionAlwaysVisible: true,
    modules: [], // Vacío porque el dashboard se renderiza directamente en el sidebar
  },
  // Gestión Principal - incluye Expedientes, Clientes, CRM
  {
    sectionCode: "gestion",
    sectionName: "Gestión",
    sectionLabel: "Gestión Principal",
    sectionIcon: "LayoutGrid",
    sectionOrder: 10,
    sectionAlwaysVisible: true,
    modules: [
      {
        moduleCode: "docket",
        moduleName: "Docket",
        moduleShortName: "Expedientes",
        moduleIcon: "FileText",
        moduleIconLucide: "FileText",
        moduleColor: "#0EA5E9",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "Todos", path: "/app/expedientes", icon: "List" },
          { label: "Plazos", path: "/app/deadlines", icon: "Calendar" },
          { label: "Crear nuevo", path: "/app/expedientes/nuevo", icon: "Plus" },
        ],
        moduleRequires: [],
        modulePopular: true,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "docs-oficiales",
        moduleName: "Docs Oficiales",
        moduleShortName: "Docs Oficiales",
        moduleIcon: "Building2",
        moduleIconLucide: "Building2",
        moduleColor: "#6366F1",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "plazos",
        moduleName: "Plazos",
        moduleShortName: "Plazos",
        moduleIcon: "CalendarClock",
        moduleIconLucide: "CalendarClock",
        moduleColor: "#EF4444",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "calendario",
        moduleName: "Calendario",
        moduleShortName: "Calendario",
        moduleIcon: "Calendar",
        moduleIconLucide: "Calendar",
        moduleColor: "#8B5CF6",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "tareas",
        moduleName: "Tareas",
        moduleShortName: "Tareas",
        moduleIcon: "CheckSquare",
        moduleIconLucide: "CheckSquare",
        moduleColor: "#10B981",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "crm",
        moduleName: "CRM",
        moduleShortName: "CRM",
        moduleIcon: "Handshake",
        moduleIconLucide: "Handshake",
        moduleColor: "#EC4899",
        moduleOrder: 3,
        moduleCategory: "addon",
        moduleExpanded: true,
        moduleMenuItems: [
          { label: "Dashboard", path: "/app/crm", icon: "LayoutDashboard" },
          { label: "Kanban", path: "/app/crm/kanban", icon: "KanbanSquare" },
          { label: "Clientes", path: "/app/crm/clients", icon: "Building2" },
          { label: "Timeline Equipo", path: "/app/crm/activities", icon: "Activity" },
          { label: "Tareas", path: "/app/crm/tasks", icon: "CheckSquare", badge: "tasks" },
        ],
        moduleRequires: [],
        modulePopular: true,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "instructions",
        moduleName: "Instrucciones",
        moduleShortName: "Instrucciones",
        moduleIcon: "ClipboardList",
        moduleIconLucide: "ClipboardList",
        moduleColor: "#6366F1",
        moduleOrder: 4,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  {
    sectionCode: "operaciones",
    sectionName: "Operaciones",
    sectionLabel: "Operaciones Diarias",
    sectionIcon: "Briefcase",
    sectionOrder: 20,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "communications",
        moduleName: "Inbox",
        moduleShortName: "Inbox",
        moduleIcon: "Inbox",
        moduleIconLucide: "Inbox",
        moduleColor: "#3B82F6",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "approvals",
        moduleName: "Aprobaciones",
        moduleShortName: "Aprobaciones",
        moduleIcon: "CheckSquare",
        moduleIconLucide: "CheckSquare",
        moduleColor: "#EF4444",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "spider",
        moduleName: "Spider",
        moduleShortName: "Vigilancia",
        moduleIcon: "Radar",
        moduleIconLucide: "Radar",
        moduleColor: "#8B5CF6",
        moduleOrder: 10,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "filing",
        moduleName: "Filing",
        moduleShortName: "Presentaciones",
        moduleIcon: "Send",
        moduleIconLucide: "Send",
        moduleColor: "#6366F1",
        moduleOrder: 11,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "workflow",
        moduleName: "Workflow",
        moduleShortName: "Flujos",
        moduleIcon: "GitBranch",
        moduleIconLucide: "GitBranch",
        moduleColor: "#0891B2",
        moduleOrder: 12,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "finance",
        moduleName: "Finance",
        moduleShortName: "Finanzas",
        moduleIcon: "DollarSign",
        moduleIconLucide: "DollarSign",
        moduleColor: "#14B8A6",
        moduleOrder: 13,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "timetracking",
        moduleName: "Timetracking",
        moduleShortName: "Tiempo",
        moduleIcon: "Clock",
        moduleIconLucide: "Clock",
        moduleColor: "#F59E0B",
        moduleOrder: 14,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "collab",
        moduleName: "Equipos",
        moduleShortName: "Colaboración",
        moduleIcon: "Users2",
        moduleIconLucide: "Users2",
        moduleColor: "#EC4899",
        moduleOrder: 15,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  {
    sectionCode: "inteligencia",
    sectionName: "Inteligencia",
    sectionLabel: "IA y Análisis",
    sectionIcon: "Brain",
    sectionOrder: 30,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "alerts",
        moduleName: "Alertas IA",
        moduleShortName: "Predicción",
        moduleIcon: "Bell",
        moduleIconLucide: "Bell",
        moduleColor: "#EF4444",
        moduleOrder: 21,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "analytics",
        moduleName: "Analytics",
        moduleShortName: "Analíticas",
        moduleIcon: "BarChart3",
        moduleIconLucide: "BarChart3",
        moduleColor: "#3B82F6",
        moduleOrder: 22,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "reportes",
        moduleName: "Reportes",
        moduleShortName: "Reportes",
        moduleIcon: "FileText",
        moduleIconLucide: "FileText",
        moduleColor: "#8B5CF6",
        moduleOrder: 23,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "legal-ops",
        moduleName: "Legal Ops",
        moduleShortName: "Operaciones",
        moduleIcon: "Scale",
        moduleIconLucide: "Scale",
        moduleColor: "#059669",
        moduleOrder: 24,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  {
    sectionCode: "extensiones",
    sectionName: "Extensiones",
    sectionLabel: "Módulos Avanzados",
    sectionIcon: "Puzzle",
    sectionOrder: 40,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "marketing",
        moduleName: "Marketing",
        moduleShortName: "Marketing",
        moduleIcon: "Megaphone",
        moduleIconLucide: "Megaphone",
        moduleColor: "#F97316",
        moduleOrder: 30,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "market",
        moduleName: "Market",
        moduleShortName: "Mercado",
        moduleIcon: "Globe",
        moduleIconLucide: "Globe",
        moduleColor: "#10B981",
        moduleOrder: 32,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "ip-chain",
        moduleName: "IP-Chain",
        moduleShortName: "Blockchain",
        moduleIcon: "Link",
        moduleIconLucide: "Link",
        moduleColor: "#6366F1",
        moduleOrder: 33,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "tools",
        moduleName: "Herramientas",
        moduleShortName: "Tools",
        moduleIcon: "Wrench",
        moduleIconLucide: "Wrench",
        moduleColor: "#64748B",
        moduleOrder: 34,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "OCR", path: "/app/tools/ocr", icon: "FileText" },
          { label: "Comparador Visual", path: "/app/tools", icon: "Eye" },
          { label: "Conectores", path: "/app/data-hub", icon: "Database" },
        ],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  {
    sectionCode: "soporte",
    sectionName: "Soporte",
    sectionLabel: "Ayuda y Soporte",
    sectionIcon: "LifeBuoy",
    sectionOrder: 50,
    sectionAlwaysVisible: true,
    modules: [
      {
        moduleCode: "help",
        moduleName: "Ayuda",
        moduleShortName: "Centro",
        moduleIcon: "HelpCircle",
        moduleIconLucide: "HelpCircle",
        moduleColor: "#6B7280",
        moduleOrder: 40,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
];

export interface SidebarMenuItem {
  label: string;
  path: string;
  icon: string;
  badge?: string;
}

export interface SidebarModule {
  moduleCode: string;
  moduleName: string;
  moduleShortName: string | null;
  moduleIcon: string;
  moduleIconLucide: string;
  moduleColor: string;
  moduleOrder: number;
  moduleCategory: string;
  moduleExpanded: boolean;
  moduleMenuItems: SidebarMenuItem[];
  moduleRequires: string[];
  modulePopular: boolean;
  moduleComingSoon: boolean;
  isLicensed: boolean;
  isTrial: boolean;
  trialEndsAt: string | null;
}

export interface SidebarSection {
  sectionCode: string;
  sectionName: string;
  sectionLabel: string;
  sectionIcon: string;
  sectionOrder: number;
  sectionAlwaysVisible: boolean;
  modules: SidebarModule[];
}

export function useSidebarMenu() {
  const { currentOrganization } = useOrganization();
  const orgId = currentOrganization?.id;

  return useQuery({
    queryKey: ["sidebar-menu", orgId],
    queryFn: async (): Promise<SidebarSection[]> => {
      if (!orgId) return [];

      // Temporalmente retornamos datos estáticos mientras se arregla la BD
      // TODO: Implementar llamada RPC cuando la estructura de BD esté lista
      return STATIC_SIDEBAR_DATA;
    },
    enabled: !!orgId,
    staleTime: Infinity, // Cache infinito para datos estáticos
  });
}

