/**
 * Hook para obtener el menú del sidebar dinámicamente desde la BD
 * Agrupa módulos por secciones y respeta licencias
 */

import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrganization } from "@/contexts/organization-context";

// Datos estáticos de fallback mientras se arregla la BD
const STATIC_SIDEBAR_DATA: SidebarSection[] = [
  // ── 0. DASHBOARD ─────────────────────────────────────
  {
    sectionCode: "dashboard",
    sectionName: "Dashboard",
    sectionLabel: "Panel",
    sectionIcon: "LayoutDashboard",
    sectionOrder: 1,
    sectionAlwaysVisible: true,
    modules: [],
  },
  // ── 1. HOY ────────────────────────────────────────────
  {
    sectionCode: "hoy",
    sectionName: "Hoy",
    sectionLabel: "HOY",
    sectionIcon: "Sunrise",
    sectionOrder: 5,
    sectionAlwaysVisible: true,
    modules: [
      {
        moduleCode: "briefing",
        moduleName: "Briefing",
        moduleShortName: "Briefing",
        moduleIcon: "Sun",
        moduleIconLucide: "Sun",
        moduleColor: "#F59E0B",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "communications",
        moduleName: "Bandeja",
        moduleShortName: "Bandeja",
        moduleIcon: "Inbox",
        moduleIconLucide: "Inbox",
        moduleColor: "#3B82F6",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "tareas",
        moduleName: "Mis Tareas",
        moduleShortName: "Tareas",
        moduleIcon: "CheckSquare",
        moduleIconLucide: "CheckSquare",
        moduleColor: "#10B981",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "calendario",
        moduleName: "Calendario",
        moduleShortName: "Calendario",
        moduleIcon: "Calendar",
        moduleIconLucide: "Calendar",
        moduleColor: "#8B5CF6",
        moduleOrder: 4,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 2. EXPEDIENTES ────────────────────────────────────
  {
    sectionCode: "expedientes",
    sectionName: "Expedientes",
    sectionLabel: "EXPEDIENTES",
    sectionIcon: "FolderOpen",
    sectionOrder: 10,
    sectionAlwaysVisible: true,
    modules: [
      {
        moduleCode: "docket",
        moduleName: "Expedientes",
        moduleShortName: "Expedientes",
        moduleIcon: "FolderOpen",
        moduleIconLucide: "FolderOpen",
        moduleColor: "#0EA5E9",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "Nuevo expediente", path: "/app/expedientes/nuevo", icon: "Plus" },
        ],
        moduleRequires: [],
        modulePopular: true,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "deadlines",
        moduleName: "Plazos",
        moduleShortName: "Plazos",
        moduleIcon: "CalendarClock",
        moduleIconLucide: "CalendarClock",
        moduleColor: "#EF4444",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "docs-oficiales",
        moduleName: "Documentos Oficiales",
        moduleShortName: "Documentos",
        moduleIcon: "Building2",
        moduleIconLucide: "Building2",
        moduleColor: "#6366F1",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "Bandeja oficial", path: "/app/smart-inbox", icon: "Building2" },
        ],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "spider",
        moduleName: "Vigilancia",
        moduleShortName: "Vigilancia",
        moduleIcon: "Radar",
        moduleIconLucide: "Radar",
        moduleColor: "#8B5CF6",
        moduleOrder: 4,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 3. CLIENTES ────────────────────────────────────────
  {
    sectionCode: "negocio",
    sectionName: "Clientes",
    sectionLabel: "CLIENTES",
    sectionIcon: "Users",
    sectionOrder: 15,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "crm-clientes",
        moduleName: "Clientes",
        moduleShortName: "Clientes",
        moduleIcon: "Users",
        moduleIconLucide: "Users",
        moduleColor: "#EC4899",
        moduleOrder: 1,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "Kanban", path: "/app/crm/kanban", icon: "KanbanSquare" },
          { label: "Tareas CRM", path: "/app/crm/tasks", icon: "CheckSquare", badge: "tasks" },
          { label: "Directorio", path: "/app/crm/clients", icon: "Building2" },
        ],
        moduleRequires: [],
        modulePopular: true,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 4. OPERACIONES ────────────────────────────────────
  {
    sectionCode: "operaciones",
    sectionName: "Operaciones",
    sectionLabel: "OPERACIONES",
    sectionIcon: "Settings2",
    sectionOrder: 20,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "filing",
        moduleName: "Presentaciones",
        moduleShortName: "Presentaciones",
        moduleIcon: "Send",
        moduleIconLucide: "Send",
        moduleColor: "#6366F1",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "finance",
        moduleName: "Finanzas",
        moduleShortName: "Finanzas",
        moduleIcon: "DollarSign",
        moduleIconLucide: "DollarSign",
        moduleColor: "#14B8A6",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "approvals",
        moduleName: "Aprobaciones",
        moduleShortName: "Aprobaciones",
        moduleIcon: "CheckSquare",
        moduleIconLucide: "CheckSquare",
        moduleColor: "#EF4444",
        moduleOrder: 3,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "timetracking",
        moduleName: "Tiempo",
        moduleShortName: "Tiempo",
        moduleIcon: "Clock",
        moduleIconLucide: "Clock",
        moduleColor: "#F59E0B",
        moduleOrder: 4,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 5. INTELIGENCIA ───────────────────────────────────
  {
    sectionCode: "inteligencia",
    sectionName: "Inteligencia",
    sectionLabel: "INTELIGENCIA",
    sectionIcon: "Brain",
    sectionOrder: 30,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "alerts",
        moduleName: "Alertas IA",
        moduleShortName: "Alertas IA",
        moduleIcon: "Bell",
        moduleIconLucide: "Bell",
        moduleColor: "#EF4444",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "spider-global",
        moduleName: "Vigilancia Global",
        moduleShortName: "Vigilancia Global",
        moduleIcon: "Globe",
        moduleIconLucide: "Globe",
        moduleColor: "#8B5CF6",
        moduleOrder: 2,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "analytics",
        moduleName: "Analytics",
        moduleShortName: "Analytics",
        moduleIcon: "BarChart3",
        moduleIconLucide: "BarChart3",
        moduleColor: "#3B82F6",
        moduleOrder: 3,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "reportes",
        moduleName: "Reportes",
        moduleShortName: "Reportes",
        moduleIcon: "FileBarChart",
        moduleIconLucide: "FileBarChart",
        moduleColor: "#8B5CF6",
        moduleOrder: 4,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "legal-ops",
        moduleName: "Legal Ops",
        moduleShortName: "Legal Ops",
        moduleIcon: "Scale",
        moduleIconLucide: "Scale",
        moduleColor: "#059669",
        moduleOrder: 5,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 6. EXTENSIONES ────────────────────────────────────
  {
    sectionCode: "extensiones",
    sectionName: "Extensiones",
    sectionLabel: "···",
    sectionIcon: "MoreHorizontal",
    sectionOrder: 40,
    sectionAlwaysVisible: false,
    modules: [
      {
        moduleCode: "market",
        moduleName: "Mercado IP",
        moduleShortName: "Mercado",
        moduleIcon: "Globe2",
        moduleIconLucide: "Globe2",
        moduleColor: "#10B981",
        moduleOrder: 1,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "ip-chain",
        moduleName: "IP-Chain",
        moduleShortName: "Blockchain",
        moduleIcon: "Link",
        moduleIconLucide: "Link",
        moduleColor: "#6366F1",
        moduleOrder: 2,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "marketing",
        moduleName: "Marketing",
        moduleShortName: "Marketing",
        moduleIcon: "Megaphone",
        moduleIconLucide: "Megaphone",
        moduleColor: "#F97316",
        moduleOrder: 3,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "workflow",
        moduleName: "Workflows",
        moduleShortName: "Flujos",
        moduleIcon: "GitBranch",
        moduleIconLucide: "GitBranch",
        moduleColor: "#0891B2",
        moduleOrder: 4,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "collab",
        moduleName: "Equipos",
        moduleShortName: "Equipos",
        moduleIcon: "Users2",
        moduleIconLucide: "Users2",
        moduleColor: "#EC4899",
        moduleOrder: 5,
        moduleCategory: "addon",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "store",
        moduleName: "Add-on Store",
        moduleShortName: "Store",
        moduleIcon: "ShoppingBag",
        moduleIconLucide: "ShoppingBag",
        moduleColor: "#10B981",
        moduleOrder: 6,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
      {
        moduleCode: "tools",
        moduleName: "Herramientas",
        moduleShortName: "Herramientas",
        moduleIcon: "Wrench",
        moduleIconLucide: "Wrench",
        moduleColor: "#64748B",
        moduleOrder: 7,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [
          { label: "OCR", path: "/app/tools/ocr", icon: "FileText" },
          { label: "Comparador Visual", path: "/app/tools", icon: "Eye" },
          { label: "Conectores", path: "/app/data-hub", icon: "Database" },
        ],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
  // ── 7. SOPORTE ────────────────────────────────────────
  {
    sectionCode: "soporte",
    sectionName: "Soporte",
    sectionLabel: "Ayuda",
    sectionIcon: "LifeBuoy",
    sectionOrder: 50,
    sectionAlwaysVisible: true,
    modules: [
      {
        moduleCode: "help",
        moduleName: "Ayuda",
        moduleShortName: "Centro de ayuda",
        moduleIcon: "HelpCircle",
        moduleIconLucide: "HelpCircle",
        moduleColor: "#6B7280",
        moduleOrder: 1,
        moduleCategory: "core",
        moduleExpanded: false,
        moduleMenuItems: [],
        moduleRequires: [],
        modulePopular: false,
        moduleComingSoon: false,
        isLicensed: true,
        isTrial: false,
        trialEndsAt: null,
      },
    ],
  },
];

export interface SidebarMenuItem {
  label: string;
  path: string;
  icon: string;
  badge?: string;
}

export interface SidebarModule {
  moduleCode: string;
  moduleName: string;
  moduleShortName: string | null;
  moduleIcon: string;
  moduleIconLucide: string;
  moduleColor: string;
  moduleOrder: number;
  moduleCategory: string;
  moduleExpanded: boolean;
  moduleMenuItems: SidebarMenuItem[];
  moduleRequires: string[];
  modulePopular: boolean;
  moduleComingSoon: boolean;
  isLicensed: boolean;
  isTrial: boolean;
  trialEndsAt: string | null;
}

export interface SidebarSection {
  sectionCode: string;
  sectionName: string;
  sectionLabel: string;
  sectionIcon: string;
  sectionOrder: number;
  sectionAlwaysVisible: boolean;
  modules: SidebarModule[];
}

export function useSidebarMenu() {
  const { currentOrganization } = useOrganization();
  const orgId = currentOrganization?.id;

  return useQuery({
    queryKey: ["sidebar-menu", orgId],
    queryFn: async (): Promise<SidebarSection[]> => {
      if (!orgId) return [];

      // Temporalmente retornamos datos estáticos mientras se arregla la BD
      // TODO: Implementar llamada RPC cuando la estructura de BD esté lista
      return STATIC_SIDEBAR_DATA;
    },
    enabled: !!orgId,
    staleTime: Infinity, // Cache infinito para datos estáticos
  });
}

