-- Remaining 120 IPO offices seed
-- Europe
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, has_api, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('BE','OPRI','Office de la Propriété Intellectuelle','OPRI','BE','Belgium','🇧🇪','europe','national',ARRAY['patent'],'Europe/Brussels',ARRAY['nl','fr','de'],'EUR',3,'E',0,'https://economie.fgov.be/fr/themes/propriete-intellectuelle',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('LU','IPIL','Office de la Propriété Intellectuelle Luxembourg','IPIL','LU','Luxembourg','🇱🇺','europe','national',ARRAY['patent'],'Europe/Luxembourg',ARRAY['fr','de','lb'],'EUR',3,'E',0,'https://guichet.public.lu/fr/entreprises/gestion-juridique-comptabilite/propriete-intellectuelle.html',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('IS','ISIPO','Icelandic Intellectual Property Office','ISIPO','IS','Iceland','🇮🇸','europe','national',ARRAY['trademark','patent','design'],'Atlantic/Reykjavik',ARRAY['is','en'],'ISK',3,'D',25,'https://www.hugverk.is',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('SK','SKIPO','Industrial Property Office of the Slovak Republic','ÚPV SR','SK','Slovakia','🇸🇰','europe','national',ARRAY['trademark','patent','design','utility_model'],'Europe/Bratislava',ARRAY['sk'],'EUR',3,'D',25,'https://www.upv.sk',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('SI','SIPO','Slovenian Intellectual Property Office','SIPO','SI','Slovenia','🇸🇮','europe','national',ARRAY['trademark','patent','design'],'Europe/Ljubljana',ARRAY['sl'],'EUR',3,'D',25,'https://www.uil-sipo.si',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('HR','SIPO-HR','State Intellectual Property Office of Croatia','DZIV','HR','Croatia','🇭🇷','europe','national',ARRAY['trademark','patent','design'],'Europe/Zagreb',ARRAY['hr'],'EUR',3,'D',25,'https://www.dziv.hr',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('UA','UKRPATENT','Ukrainian Intellectual Property Institute','Ukrpatent','UA','Ukraine','🇺🇦','europe','national',ARRAY['trademark','patent','design','utility_model'],'Europe/Kyiv',ARRAY['uk'],'UAH',3,'D',25,'https://ukrpatent.org',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('BY','NCIP','National Center of Intellectual Property','NCIP','BY','Belarus','🇧🇾','europe','national',ARRAY['trademark','patent','design','utility_model'],'Europe/Minsk',ARRAY['be','ru'],'BYN',3,'E',0,'https://ncip.by',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('MD','AGEPI','State Agency on Intellectual Property','AGEPI','MD','Moldova','🇲🇩','europe','national',ARRAY['trademark','patent','design'],'Europe/Chisinau',ARRAY['ro','ru'],'MDL',3,'E',0,'https://agepi.gov.md',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('BG','BPO','Patent Office of the Republic of Bulgaria','BPO','BG','Bulgaria','🇧🇬','europe','national',ARRAY['trademark','patent','design','utility_model'],'Europe/Sofia',ARRAY['bg'],'BGN',3,'D',25,'https://www.bpo.bg',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('RS','IPO-RS','Intellectual Property Office of Serbia','ZIS','RS','Serbia','🇷🇸','europe','national',ARRAY['trademark','patent','design'],'Europe/Belgrade',ARRAY['sr'],'RSD',3,'E',0,'https://www.zis.gov.rs',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('BA','IIP-BH','Institute for Intellectual Property of Bosnia and Herzegovina','IIP BiH','BA','Bosnia and Herzegovina','🇧🇦','europe','national',ARRAY['trademark','patent','design'],'Europe/Sarajevo',ARRAY['bs','hr','sr'],'BAM',3,'E',0,'https://www.ipr.gov.ba',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('ME','IPO-ME','Intellectual Property Office of Montenegro','ZISCG','ME','Montenegro','🇲🇪','europe','national',ARRAY['trademark','patent','design'],'Europe/Podgorica',ARRAY['sr'],'EUR',3,'E',0,'https://www.ziscg.me',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('MK','SOIP','State Office of Industrial Property','SOIP','MK','North Macedonia','🇲🇰','europe','national',ARRAY['trademark','patent','design'],'Europe/Skopje',ARRAY['mk'],'MKD',3,'E',0,'http://www.ippo.gov.mk',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('AL','DPPM','General Directorate of Patents and Trademarks','DPPM','AL','Albania','🇦🇱','europe','national',ARRAY['trademark','patent','design'],'Europe/Tirane',ARRAY['sq'],'ALL',3,'E',0,'https://www.dppm.gov.al',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('XK','IPO-XK','Industrial Property Agency of Kosovo','IPA','XK','Kosovo','🇽🇰','europe','national',ARRAY['trademark','patent','design'],'Europe/Belgrade',ARRAY['sq','sr'],'EUR',3,'E',0,'https://api-ks.org',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('LV','LRPV','Patent Office of the Republic of Latvia','LRPV','LV','Latvia','🇱🇻','europe','national',ARRAY['trademark','patent','design'],'Europe/Riga',ARRAY['lv'],'EUR',3,'D',25,'https://www.lrpv.gov.lv',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('LT','SPB','State Patent Bureau of the Republic of Lithuania','VPB','LT','Lithuania','🇱🇹','europe','national',ARRAY['trademark','patent','design'],'Europe/Vilnius',ARRAY['lt'],'EUR',3,'D',25,'https://www.vpb.lt',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('CY','DRCOR','Department of Registrar of Companies and Intellectual Property','DRCOR','CY','Cyprus','🇨🇾','europe','national',ARRAY['trademark','patent','design'],'Asia/Nicosia',ARRAY['el','en'],'EUR',3,'D',25,'https://www.companies.gov.cy',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('MT','IPMALTA','Industrial Property Registrations Directorate','IP Malta','MT','Malta','🇲🇹','europe','national',ARRAY['trademark','patent','design'],'Europe/Malta',ARRAY['mt','en'],'EUR',3,'D',25,'https://commerce.gov.mt/ip',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('GE','SAKPATENTI','National Intellectual Property Center of Georgia','Sakpatenti','GE','Georgia','🇬🇪','europe','national',ARRAY['trademark','patent','design'],'Asia/Tbilisi',ARRAY['ka'],'GEL',3,'D',25,'https://www.sakpatenti.gov.ge',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('AM','AIPA','Intellectual Property Agency of Armenia','AIPA','AM','Armenia','🇦🇲','europe','national',ARRAY['trademark','patent','design'],'Asia/Yerevan',ARRAY['hy'],'AMD',3,'E',0,'https://www.aipa.am',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('AZ','COPAT','Intellectual Property Agency of Azerbaijan','COPAT','AZ','Azerbaijan','🇦🇿','europe','national',ARRAY['trademark','patent','design'],'Asia/Baku',ARRAY['az'],'AZN',3,'E',0,'https://copat.gov.az',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('MC',NULL,'Direction du Développement Économique','Monaco IP','MC','Monaco','🇲🇨','europe','national',ARRAY['trademark','patent'],'Europe/Monaco',ARRAY['fr'],'EUR',3,'E',0,'https://en.gouv.mc/Policy-Practice/Economic-Development',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('SM','USBM','Ufficio di Stato Brevetti e Marchi','USBM','SM','San Marino','🇸🇲','europe','national',ARRAY['trademark','patent'],'Europe/San_Marino',ARRAY['it'],'EUR',3,'E',0,'https://www.usbm.sm',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('LI','AVW','Office for Economic Affairs','AVW','LI','Liechtenstein','🇱🇮','europe','national',ARRAY['trademark','patent'],'Europe/Vaduz',ARRAY['de'],'CHF',3,'E',0,'https://www.llv.li/inhalt/11317/amtsstellen/amt-fur-volkswirtschaft',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('AD','OMPA','Oficina de Marques i Patents d''Andorra','OMPA','AD','Andorra','🇦🇩','europe','national',ARRAY['trademark','patent'],'Europe/Andorra',ARRAY['ca'],'EUR',3,'E',0,'https://www.ompa.ad',FALSE,FALSE,FALSE,NULL,'active',TRUE,30)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;

-- Americas
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, has_api, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('BZ',NULL,'Belize Intellectual Property Office','BELIPO','BZ','Belize','🇧🇿','latin_america','national',ARRAY['trademark','patent'],'America/Belize',ARRAY['en'],'BZD',3,'E',0,'https://belipo.bz',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('HN','DIGEPIH','Dirección General de Propiedad Intelectual','DIGEPIH','HN','Honduras','🇭🇳','latin_america','national',ARRAY['trademark','patent','design'],'America/Tegucigalpa',ARRAY['es'],'HNL',3,'E',0,'https://www.ip.gob.hn',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('SV','CNR','Centro Nacional de Registros','CNR','SV','El Salvador','🇸🇻','latin_america','national',ARRAY['trademark','patent','design'],'America/El_Salvador',ARRAY['es'],'USD',3,'E',0,'https://www.cnr.gob.sv',FALSE,TRUE,FALSE,NULL,'active',TRUE,30),
('NI','RPI-NI','Registro de la Propiedad Intelectual','RPI Nicaragua','NI','Nicaragua','🇳🇮','latin_america','national',ARRAY['trademark','patent','design'],'America/Managua',ARRAY['es'],'NIO',3,'E',0,'https://www.mific.gob.ni',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('CU','OCPI','Oficina Cubana de la Propiedad Industrial','OCPI','CU','Cuba','🇨🇺','caribbean','national',ARRAY['trademark','patent','design'],'America/Havana',ARRAY['es'],'CUP',3,'E',0,'https://www.ocpi.cu',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('HT',NULL,'Direction de la Propriété Industrielle','DPI Haiti','HT','Haiti','🇭🇹','caribbean','national',ARRAY['trademark','patent'],'America/Port-au-Prince',ARRAY['fr','ht'],'HTG',3,'E',0,'https://www.mci.gouv.ht',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('JM','JIPO','Jamaica Intellectual Property Office','JIPO','JM','Jamaica','🇯🇲','caribbean','national',ARRAY['trademark','patent','design'],'America/Jamaica',ARRAY['en'],'JMD',3,'D',25,'https://www.jipo.gov.jm',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('TT','TTIPO','Trinidad and Tobago Intellectual Property Office','TTIPO','TT','Trinidad and Tobago','🇹🇹','caribbean','national',ARRAY['trademark','patent','design'],'America/Port_of_Spain',ARRAY['en'],'TTD',3,'D',25,'https://www.ipo.gov.tt',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('BB','CAIPO','Corporate Affairs and Intellectual Property Office','CAIPO','BB','Barbados','🇧🇧','caribbean','national',ARRAY['trademark','patent'],'America/Barbados',ARRAY['en'],'BBD',3,'E',0,'https://caipo.gov.bb',FALSE,TRUE,FALSE,NULL,'active',TRUE,30),
('BS',NULL,'Registrar General''s Department','RGD Bahamas','BS','Bahamas','🇧🇸','caribbean','national',ARRAY['trademark','patent'],'America/Nassau',ARRAY['en'],'BSD',3,'E',0,'https://www.bahamas.gov.bs',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('PR',NULL,'Puerto Rico Trademark Office','PR State','PR','Puerto Rico','🇵🇷','caribbean','national',ARRAY['trademark'],'America/Puerto_Rico',ARRAY['es','en'],'USD',3,'D',25,'https://estado.pr.gov',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('VE','SAPI','Servicio Autónomo de la Propiedad Intelectual','SAPI','VE','Venezuela','🇻🇪','latin_america','national',ARRAY['trademark','patent','design'],'America/Caracas',ARRAY['es'],'VES',3,'E',0,'http://www.sapi.gob.ve',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('BO','SENAPI','Servicio Nacional de Propiedad Intelectual','SENAPI','BO','Bolivia','🇧🇴','latin_america','national',ARRAY['trademark','patent','design'],'America/La_Paz',ARRAY['es'],'BOB',3,'E',0,'https://www.senapi.gob.bo',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('PY','DINAPI','Dirección Nacional de Propiedad Intelectual','DINAPI','PY','Paraguay','🇵🇾','latin_america','national',ARRAY['trademark','patent','design'],'America/Asuncion',ARRAY['es','gn'],'PYG',3,'E',0,'https://www.dinapi.gov.py',FALSE,TRUE,FALSE,NULL,'active',TRUE,30),
('GY',NULL,'Deeds and Commercial Registries','Deeds Registry','GY','Guyana','🇬🇾','latin_america','national',ARRAY['trademark','patent'],'America/Guyana',ARRAY['en'],'GYD',3,'E',0,'https://www.minleg.gov.gy',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('SR',NULL,'Bureau Intellectuele Eigendom','BIE','SR','Suriname','🇸🇷','latin_america','national',ARRAY['trademark','patent'],'America/Paramaribo',ARRAY['nl'],'SRD',3,'E',0,'https://www.gov.sr',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('AG',NULL,'Antigua and Barbuda Intellectual Property Office','ABIPO','AG','Antigua and Barbuda','🇦🇬','caribbean','national',ARRAY['trademark','patent'],'America/Antigua',ARRAY['en'],'XCD',3,'E',0,'https://abipo.gov.ag',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('DM',NULL,'Dominica Intellectual Property Office','Dominica IPO','DM','Dominica','🇩🇲','caribbean','national',ARRAY['trademark','patent'],'America/Dominica',ARRAY['en'],'XCD',3,'E',0,'https://commerce.gov.dm',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('GD',NULL,'Grenada Intellectual Property Office','Grenada IPO','GD','Grenada','🇬🇩','caribbean','national',ARRAY['trademark','patent'],'America/Grenada',ARRAY['en'],'XCD',3,'E',0,'https://www.gov.gd',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('KN',NULL,'Saint Kitts and Nevis Intellectual Property Office','SKNIPO','KN','Saint Kitts and Nevis','🇰🇳','caribbean','national',ARRAY['trademark','patent'],'America/St_Kitts',ARRAY['en'],'XCD',3,'E',0,'https://www.gov.kn',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('LC',NULL,'Registry of Companies and Intellectual Property','RCIP','LC','Saint Lucia','🇱🇨','caribbean','national',ARRAY['trademark','patent'],'America/St_Lucia',ARRAY['en'],'XCD',3,'E',0,'https://www.rcip.gov.lc',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('VC',NULL,'Commerce and Intellectual Property Office','CIPO SVG','VC','Saint Vincent and the Grenadines','🇻🇨','caribbean','national',ARRAY['trademark','patent'],'America/St_Vincent',ARRAY['en'],'XCD',3,'E',0,'https://www.gov.vc',FALSE,FALSE,FALSE,NULL,'active',TRUE,30)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;

-- Asia-Pacific
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, has_api, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('MO',NULL,'Macao Economic and Technological Development Bureau','DSEDT','MO','Macao','🇲🇴','asia_pacific','national',ARRAY['trademark','patent'],'Asia/Macau',ARRAY['zh','pt'],'MOP',3,'D',25,'https://www.economia.gov.mo',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('MN','IPOM','Intellectual Property Office of Mongolia','IPOM','MN','Mongolia','🇲🇳','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Ulaanbaatar',ARRAY['mn'],'MNT',3,'E',0,'https://www.ipom.mn',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('KP',NULL,'Trademark, Industrial Design and Geographical Indication Office','TIDGIO','KP','North Korea','🇰🇵','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Pyongyang',ARRAY['ko'],'KPW',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('BN','BruIPO','Brunei Intellectual Property Office','BruIPO','BN','Brunei','🇧🇳','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Brunei',ARRAY['ms','en'],'BND',3,'D',25,'https://www.bruipo.gov.bn',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('KH','MoC-KH','Department of Intellectual Property','DIP Cambodia','KH','Cambodia','🇰🇭','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Phnom_Penh',ARRAY['km'],'KHR',3,'E',0,'https://www.cambodiaip.gov.kh',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('LA','MOIC-LA','Department of Intellectual Property','DIP Laos','LA','Laos','🇱🇦','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Vientiane',ARRAY['lo'],'LAK',3,'E',0,'https://www.moic.gov.la',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('MM','IPOM-MM','Intellectual Property Office of Myanmar','IPO Myanmar','MM','Myanmar','🇲🇲','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Yangon',ARRAY['my'],'MMK',3,'E',0,'https://www.ipd.gov.mm',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('TL',NULL,'National Directorate of Intellectual Property','DNPI Timor-Leste','TL','Timor-Leste','🇹🇱','asia_pacific','national',ARRAY['trademark','patent'],'Asia/Dili',ARRAY['pt','tet'],'USD',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('PK','IPO-PK','Intellectual Property Organization of Pakistan','IPO Pakistan','PK','Pakistan','🇵🇰','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Karachi',ARRAY['ur','en'],'PKR',3,'D',25,'https://www.ipo.gov.pk',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('BD','DPDT','Department of Patents, Designs and Trademarks','DPDT','BD','Bangladesh','🇧🇩','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Dhaka',ARRAY['bn'],'BDT',3,'E',0,'http://www.dpdt.gov.bd',FALSE,TRUE,FALSE,NULL,'active',TRUE,30),
('LK','NIPO-LK','National Intellectual Property Office','NIPO Sri Lanka','LK','Sri Lanka','🇱🇰','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Colombo',ARRAY['si','ta','en'],'LKR',3,'D',25,'https://www.nipo.gov.lk',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('NP','DOIP','Department of Industry','DoIP Nepal','NP','Nepal','🇳🇵','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Kathmandu',ARRAY['ne'],'NPR',3,'E',0,'https://www.doind.gov.np',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('BT',NULL,'Department of Intellectual Property','DIP Bhutan','BT','Bhutan','🇧🇹','asia_pacific','national',ARRAY['trademark','patent'],'Asia/Thimphu',ARRAY['dz'],'BTN',3,'E',0,'https://www.moea.gov.bt',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('MV',NULL,'Maldives Intellectual Property Office','MIPO','MV','Maldives','🇲🇻','asia_pacific','national',ARRAY['trademark','patent'],'Indian/Maldives',ARRAY['dv','en'],'MVR',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('AF',NULL,'Afghanistan Central Business Registry and Intellectual Property','ACBRIP','AF','Afghanistan','🇦🇫','asia_pacific','national',ARRAY['trademark','patent'],'Asia/Kabul',ARRAY['ps','fa'],'AFN',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('KZ','NIIP','National Institute of Intellectual Property','NIIP Kazakhstan','KZ','Kazakhstan','🇰🇿','asia_pacific','national',ARRAY['trademark','patent','design','utility_model'],'Asia/Almaty',ARRAY['kk','ru'],'KZT',3,'D',25,'https://www.kazpatent.kz',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('UZ','IPA-UZ','Intellectual Property Agency','IPA Uzbekistan','UZ','Uzbekistan','🇺🇿','asia_pacific','national',ARRAY['trademark','patent','design','utility_model'],'Asia/Tashkent',ARRAY['uz','ru'],'UZS',3,'E',0,'https://www.ima.uz',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('TJ','NCPI-TJ','National Center for Patents and Information','NCPI Tajikistan','TJ','Tajikistan','🇹🇯','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Dushanbe',ARRAY['tg','ru'],'TJS',3,'E',0,'https://www.ncpi.tj',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('KG','KYRGYZPATENT','State Service of Intellectual Property and Innovation','Kyrgyzpatent','KG','Kyrgyzstan','🇰🇬','asia_pacific','national',ARRAY['trademark','patent','design','utility_model'],'Asia/Bishkek',ARRAY['ky','ru'],'KGS',3,'E',0,'https://www.patent.kg',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('TM','SIPIST','State Service of Intellectual Property','SIPIST','TM','Turkmenistan','🇹🇲','asia_pacific','national',ARRAY['trademark','patent','design'],'Asia/Ashgabat',ARRAY['tk','ru'],'TMT',3,'E',0,'https://www.turkmenpatent.gov.tm',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('FJ',NULL,'Fiji Intellectual Property Office','FIPO','FJ','Fiji','🇫🇯','oceania','national',ARRAY['trademark','patent'],'Pacific/Fiji',ARRAY['en','fj','hi'],'FJD',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('PG','IPOPNG','Intellectual Property Office of Papua New Guinea','IPOPNG','PG','Papua New Guinea','🇵🇬','oceania','national',ARRAY['trademark','patent'],'Pacific/Port_Moresby',ARRAY['en','tpi','ho'],'PGK',3,'E',0,'https://www.ipopng.gov.pg',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('WS',NULL,'Samoa Intellectual Property Office','Samoa IPO','WS','Samoa','🇼🇸','oceania','national',ARRAY['trademark','patent'],'Pacific/Apia',ARRAY['sm','en'],'WST',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('TO',NULL,'Tonga Intellectual Property Office','Tonga IPO','TO','Tonga','🇹🇴','oceania','national',ARRAY['trademark','patent'],'Pacific/Tongatapu',ARRAY['to','en'],'TOP',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('VU',NULL,'Vanuatu Intellectual Property Office','Vanuatu IPO','VU','Vanuatu','🇻🇺','oceania','national',ARRAY['trademark','patent'],'Pacific/Efate',ARRAY['bi','en','fr'],'VUV',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;

-- Middle East
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, has_api, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('QA','QIPO','Qatar Intellectual Property Office','QIPO','QA','Qatar','🇶🇦','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Qatar',ARRAY['ar','en'],'QAR',2,'D',25,'https://www.moci.gov.qa',FALSE,TRUE,TRUE,NULL,'active',TRUE,60),
('KW','MOCI-KW','Ministry of Commerce and Industry - Trademarks Office','Kuwait TMO','KW','Kuwait','🇰🇼','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Kuwait',ARRAY['ar'],'KWD',3,'D',25,'https://www.moci.gov.kw',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('BH','MOIC-BH','Ministry of Industry and Commerce','Bahrain IP','BH','Bahrain','🇧🇭','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Bahrain',ARRAY['ar','en'],'BHD',3,'D',25,'https://www.moic.gov.bh',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('OM','MOCI-OM','Ministry of Commerce, Industry and Investment Promotion','Oman IP','OM','Oman','🇴🇲','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Muscat',ARRAY['ar'],'OMR',3,'D',25,'https://www.moci.gov.om',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('YE',NULL,'Ministry of Industry and Trade','Yemen IP','YE','Yemen','🇾🇪','middle_east','national',ARRAY['trademark','patent'],'Asia/Aden',ARRAY['ar'],'YER',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('JO','IPRP-JO','Industrial Property Protection Directorate','Jordan IP','JO','Jordan','🇯🇴','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Amman',ARRAY['ar'],'JOD',3,'D',25,'https://www.mit.gov.jo',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('LB','IPO-LB','Intellectual Property Office','Lebanon IP','LB','Lebanon','🇱🇧','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Beirut',ARRAY['ar','fr'],'LBP',3,'E',0,'https://www.economy.gov.lb',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('SY',NULL,'Directorate of Commercial and Industrial Property Protection','Syria IP','SY','Syria','🇸🇾','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Damascus',ARRAY['ar'],'SYP',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('IQ','COSQC','Central Organization for Standardization and Quality Control','Iraq IP','IQ','Iraq','🇮🇶','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Baghdad',ARRAY['ar','ku'],'IQD',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('PS',NULL,'Palestinian Ministry of National Economy','Palestine IP','PS','Palestine','🇵🇸','middle_east','national',ARRAY['trademark','patent'],'Asia/Gaza',ARRAY['ar'],'ILS',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('IR','IRSIPO','State Registration Organization of Deeds and Properties','Iran IP','IR','Iran','🇮🇷','middle_east','national',ARRAY['trademark','patent','design'],'Asia/Tehran',ARRAY['fa'],'IRR',2,'D',25,'https://iripo.ssaa.ir',FALSE,TRUE,FALSE,TRUE,'active',TRUE,60)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;

-- Africa
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, has_api, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('DZ','INAPI-DZ','Institut National Algérien de la Propriété Industrielle','INAPI Algeria','DZ','Algeria','🇩🇿','africa','national',ARRAY['trademark','patent','design'],'Africa/Algiers',ARRAY['ar','fr'],'DZD',3,'D',25,'https://www.inapi.org',FALSE,TRUE,FALSE,TRUE,'active',TRUE,30),
('LY',NULL,'Libyan Industrial Property Office','Libya IP','LY','Libya','🇱🇾','africa','national',ARRAY['trademark','patent'],'Africa/Tripoli',ARRAY['ar'],'LYD',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('SD',NULL,'Registrar General of Intellectual Property','Sudan IP','SD','Sudan','🇸🇩','africa','national',ARRAY['trademark','patent'],'Africa/Khartoum',ARRAY['ar','en'],'SDG',3,'E',0,'https://www.ipr.gov.sd',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('GH','RGD-GH','Registrar-General''s Department','Ghana IP','GH','Ghana','🇬🇭','africa','national',ARRAY['trademark','patent','design'],'Africa/Accra',ARRAY['en'],'GHS',3,'D',25,'https://rgd.gov.gh',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('SN','ASPIT','Agence Sénégalaise pour la Propriété Industrielle et l''Innovation Technologique','ASPIT','SN','Senegal','🇸🇳','africa','national',ARRAY['trademark','patent','design'],'Africa/Dakar',ARRAY['fr'],'XOF',3,'E',0,'https://www.aspit.sn',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('CI','OIPI','Office Ivoirien de la Propriété Intellectuelle','OIPI','CI','Ivory Coast','🇨🇮','africa','national',ARRAY['trademark','patent','design'],'Africa/Abidjan',ARRAY['fr'],'XOF',3,'E',0,'https://www.oipi.ci',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('CM','MINDCAF','Ministry of Mines, Industry and Technological Development','Cameroon IP','CM','Cameroon','🇨🇲','africa','national',ARRAY['trademark','patent','design'],'Africa/Douala',ARRAY['fr','en'],'XAF',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('LR',NULL,'Liberia Intellectual Property Office','LIPO','LR','Liberia','🇱🇷','africa','national',ARRAY['trademark','patent'],'Africa/Monrovia',ARRAY['en'],'LRD',3,'E',0,'https://www.lipo.gov.lr',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('SL',NULL,'Sierra Leone Intellectual Property Office','SLIPO','SL','Sierra Leone','🇸🇱','africa','national',ARRAY['trademark','patent'],'Africa/Freetown',ARRAY['en'],'SLL',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('CV',NULL,'Instituto da Qualidade e Propriedade Intelectual','IQPI','CV','Cape Verde','🇨🇻','africa','national',ARRAY['trademark','patent'],'Atlantic/Cape_Verde',ARRAY['pt'],'CVE',3,'E',0,'https://www.iqpi.cv',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('TZ','BRELA','Business Registrations and Licensing Agency','BRELA','TZ','Tanzania','🇹🇿','africa','national',ARRAY['trademark','patent','design'],'Africa/Dar_es_Salaam',ARRAY['sw','en'],'TZS',3,'E',0,'https://www.brela.go.tz',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('UG','URSB','Uganda Registration Services Bureau','URSB','UG','Uganda','🇺🇬','africa','national',ARRAY['trademark','patent','design'],'Africa/Kampala',ARRAY['en','sw'],'UGX',3,'E',0,'https://www.ursb.go.ug',FALSE,TRUE,TRUE,NULL,'active',TRUE,30),
('RW','RDB','Rwanda Development Board','RDB Rwanda','RW','Rwanda','🇷🇼','africa','national',ARRAY['trademark','patent','design'],'Africa/Kigali',ARRAY['rw','en','fr'],'RWF',3,'D',25,'https://www.rdb.rw',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('ET','EIPO','Ethiopian Intellectual Property Office','EIPO','ET','Ethiopia','🇪🇹','africa','national',ARRAY['trademark','patent','design'],'Africa/Addis_Ababa',ARRAY['am','en'],'ETB',3,'E',0,'https://www.eipo.gov.et',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('MU','IPOM','Industrial Property Office of Mauritius','IPOM','MU','Mauritius','🇲🇺','africa','national',ARRAY['trademark','patent','design'],'Indian/Mauritius',ARRAY['en','fr'],'MUR',3,'D',25,'https://foreign.govmu.org',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('MG','OMAPI','Office Malgache de la Propriété Industrielle','OMAPI','MG','Madagascar','🇲🇬','africa','national',ARRAY['trademark','patent','design'],'Indian/Antananarivo',ARRAY['mg','fr'],'MGA',3,'E',0,'https://www.omapi.mg',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('SC',NULL,'Seychelles Intellectual Property Office','SIPO','SC','Seychelles','🇸🇨','africa','national',ARRAY['trademark','patent'],'Indian/Mahe',ARRAY['en','fr','crs'],'SCR',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('BW','CIPA','Companies and Intellectual Property Authority','CIPA','BW','Botswana','🇧🇼','africa','national',ARRAY['trademark','patent','design'],'Africa/Gaborone',ARRAY['en','tn'],'BWP',3,'D',25,'https://www.cipa.co.bw',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('NA','BIPA','Business and Intellectual Property Authority','BIPA','NA','Namibia','🇳🇦','africa','national',ARRAY['trademark','patent','design'],'Africa/Windhoek',ARRAY['en'],'NAD',3,'D',25,'https://www.bipa.na',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('ZW','ZIPO','Zimbabwe Intellectual Property Office','ZIPO','ZW','Zimbabwe','🇿🇼','africa','national',ARRAY['trademark','patent','design'],'Africa/Harare',ARRAY['en','sn','nd'],'ZWL',3,'E',0,'https://www.zipo.co.zw',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('ZM','PACRA','Patents and Companies Registration Agency','PACRA','ZM','Zambia','🇿🇲','africa','national',ARRAY['trademark','patent','design'],'Africa/Lusaka',ARRAY['en'],'ZMW',3,'D',25,'https://www.pacra.org.zm',FALSE,TRUE,TRUE,TRUE,'active',TRUE,30),
('MW',NULL,'Registrar General - IP Office','Malawi IP','MW','Malawi','🇲🇼','africa','national',ARRAY['trademark','patent'],'Africa/Blantyre',ARRAY['en','ny'],'MWK',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('MZ','IPI-MZ','Instituto da Propriedade Industrial','IPI Mozambique','MZ','Mozambique','🇲🇿','africa','national',ARRAY['trademark','patent','design'],'Africa/Maputo',ARRAY['pt'],'MZN',3,'E',0,'https://www.ipi.gov.mz',FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('AO','IAPI','Instituto Angolano da Propriedade Industrial','IAPI','AO','Angola','🇦🇴','africa','national',ARRAY['trademark','patent','design'],'Africa/Luanda',ARRAY['pt'],'AOA',3,'E',0,'https://www.iapi.ao',FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('SZ',NULL,'Eswatini Intellectual Property Office','Eswatini IP','SZ','Eswatini','🇸🇿','africa','national',ARRAY['trademark','patent'],'Africa/Mbabane',ARRAY['en','ss'],'SZL',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('LS',NULL,'Registrar General','Lesotho IP','LS','Lesotho','🇱🇸','africa','national',ARRAY['trademark','patent'],'Africa/Maseru',ARRAY['en','st'],'LSL',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30),
('KM',NULL,'Agence Nationale de la Propriété Industrielle','ANPI Comoros','KM','Comoros','🇰🇲','africa','national',ARRAY['trademark','patent'],'Indian/Comoro',ARRAY['ar','fr'],'KMF',3,'E',0,NULL,FALSE,FALSE,FALSE,NULL,'active',TRUE,30),
('ST',NULL,'Instituto Nacional da Propriedade Industrial','STP IP','ST','São Tomé and Príncipe','🇸🇹','africa','national',ARRAY['trademark','patent'],'Africa/Sao_Tome',ARRAY['pt'],'STN',3,'E',0,NULL,FALSE,FALSE,FALSE,TRUE,'active',TRUE,30)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;

-- International (remaining)
INSERT INTO ipo_offices (code, code_alt, name_official, name_short, country_code, country_name, flag_emoji, region, office_type, ip_types, timezone, languages, currency, tier, automation_level, automation_percentage, website_official, website_search, has_api, api_type, e_filing_available, online_payment, member_madrid_protocol, status, is_active, priority_score) VALUES
('EM','EUIPO','European Union Intellectual Property Office','EUIPO',NULL,'European Union','🇪🇺','europe','regional',ARRAY['trademark','design'],'Europe/Madrid',ARRAY['en','es','de','fr','it'],'EUR',1,'A',100,'https://euipo.europa.eu','https://euipo.europa.eu/eSearch/',TRUE,'REST',TRUE,TRUE,TRUE,'active',TRUE,90),
('BX','BOIP','Benelux Office for Intellectual Property','BOIP',NULL,'Benelux','🇧🇪','europe','regional',ARRAY['trademark','design'],'Europe/Amsterdam',ARRAY['nl','fr','en'],'EUR',2,'C',50,'https://www.boip.int','https://www.boip.int/en/trademark-search',FALSE,NULL,TRUE,TRUE,TRUE,'active',TRUE,60),
('EA','EAPO','Eurasian Patent Organization','EAPO',NULL,'Eurasia','🌍','europe','regional',ARRAY['patent','design'],'Europe/Moscow',ARRAY['ru','en'],'USD',2,'D',25,'https://www.eapo.org',NULL,FALSE,NULL,TRUE,TRUE,NULL,'active',TRUE,60),
('AP','ARIPO','African Regional Intellectual Property Organization','ARIPO',NULL,'Africa (Anglophone)','🌍','africa','regional',ARRAY['trademark','patent','design'],'Africa/Harare',ARRAY['en'],'USD',2,'D',25,'https://www.aripo.org',NULL,FALSE,NULL,TRUE,FALSE,TRUE,'active',TRUE,60),
('OA','OAPI','Organisation Africaine de la Propriété Intellectuelle','OAPI',NULL,'Africa (Francophone)','🌍','africa','regional',ARRAY['trademark','patent','design'],'Africa/Douala',ARRAY['fr'],'XAF',2,'E',0,'https://oapi.int',NULL,FALSE,NULL,FALSE,FALSE,TRUE,'active',TRUE,60),
('GC','GCCPO','Patent Office of the Cooperation Council for the Arab States of the Gulf','GCCPO',NULL,'Gulf States','🌍','middle_east','regional',ARRAY['patent'],'Asia/Riyadh',ARRAY['ar','en'],'SAR',2,'E',0,'https://www.gccpo.org',NULL,FALSE,NULL,FALSE,FALSE,NULL,'active',TRUE,60)
ON CONFLICT (code) DO UPDATE SET name_official=EXCLUDED.name_official, name_short=EXCLUDED.name_short, country_name=EXCLUDED.country_name, flag_emoji=EXCLUDED.flag_emoji, region=EXCLUDED.region, office_type=EXCLUDED.office_type, ip_types=EXCLUDED.ip_types, timezone=EXCLUDED.timezone, languages=EXCLUDED.languages, currency=EXCLUDED.currency, tier=EXCLUDED.tier, automation_level=EXCLUDED.automation_level, automation_percentage=EXCLUDED.automation_percentage;