-- Añadir Colombia a la tabla de jurisdicciones
INSERT INTO jurisdictions (
  code,
  name,
  name_en,
  name_es,
  jurisdiction_type,
  tier,
  region,
  ipo_name,
  office_acronym,
  office_website,
  official_languages,
  filing_languages,
  currency_code,
  timezone,
  phone_code,
  supports_trademarks,
  supports_patents,
  supports_utility_models,
  supports_designs,
  is_madrid_member,
  is_pct_member,
  is_hague_member,
  is_paris_member,
  paris_priority_months_tm,
  paris_priority_months_pt,
  paris_priority_months_ds,
  opposition_period_days,
  trademark_duration_years,
  patent_duration_years,
  requires_local_agent,
  requires_translation,
  has_subclasses,
  use_requirement,
  use_declaration_required,
  flag_emoji,
  flag_code,
  has_knowledge_base,
  has_spider_monitoring,
  has_deadline_rules,
  has_official_forms,
  has_api_integration,
  price_monthly,
  is_active,
  sort_order
) VALUES (
  'CO',
  'Colombia (SIC)',
  'Colombia',
  'Colombia',
  'country',
  2,
  'LATAM',
  'Superintendencia de Industria y Comercio',
  'SIC',
  'https://www.sic.gov.co',
  ARRAY['es'],
  ARRAY['es'],
  'COP',
  'America/Bogota',
  '+57',
  true,
  true,
  true,
  true,
  false,  -- No es miembro de Madrid
  true,   -- Es miembro PCT
  false,  -- No es miembro de Hague
  true,   -- Es miembro de París
  6,
  12,
  6,
  30,
  10,
  20,
  true,
  true,
  false,
  true,
  false,
  '🇨🇴',
  'co',
  false,
  false,
  true,
  true,
  false,
  0,
  true,
  150
);