// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaqniahteuzhetuyzvak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcW5pYWh0ZXV6aGV0dXl6dmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NTI5MjEsImV4cCI6MjA4OTQyODkyMX0.3z-NyjVkjqUMOIER-q2bVrWTf3M3RbZecJ1erinb0M8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});